# префикс для всех переменных
[1.5]

# IP
45.55.6.12.ip = '0.0.0.0'

# IP
45.55.6.13.ip = '192.168.0.1'

# OCTET STRING
4.55.66 = "Test string"

# OCTET STRING
4.55.67 = "Other text"

# INTEGER
4.56.66 = 1010

# INTEGER
4.56.67 = 2021




